# run command for load .env file
# docker-compose --env-file .env config

version: '3'
services:
  app:
    build:
      context: docker/php
      dockerfile: docker/php/Dockerfile
    image: php:7.4-fpm
    restart: unless-stopped
    container_name: app
    environment:
        SERVICE_NAME: app
        SERVICE_TAGS: dev
    working_dir: /var/www
    volumes:
        - ./:/var/www
        - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
        - laravel-app-network

# Web service Nginx
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "8099:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./docker/nginx/nginx:/etc/nginx
    networks:
      - laravel-app-network
# Mysql
  db:
    build:
      context: docker/mysql
      dockerfile: docker/mysql/Dockerfile

    # restart container when container stop
    restart: unless-stopped
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    ports:
      - "${DB_PUBLIC_PORT}:3306"
    volumes:
      - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
      - ./log/mysql:/var/log/mysql
      - mysql_data:/var/lib/mysql
    networks:
        - laravel-app-network

# adminer
  adminer:
    build:
      context: docker/adminer
      dockerfile: docker/adminer/Dockerfile
    image: unless-stopped
    restart: always
    ports:
      - "${ADMINER_PORT}:8080"
    networks:
        - laravel-app-network

#Docker networks:
networks:
  laravel-app-network:
    driver: bridge

# create volume
volumes:
  mysql_data: {}


